# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# needed to install the sf package
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable' # for sf
    packages:
      # sf
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
